### ISSUE TITLE
Compilation error on 0.4.0.0

### ISSUE THREAD

**Issue by badeleux** [expipiplus1/vector-sized#9]
```
   [1 of 3] Compiling Data.Vector.Generic.Sized ( src/Data/Vector/Generic/Sized.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/Data/Vector/Generic/Sized.o )
    
    /private/var/folders/x7/4dq_h8_j2zx27372y1qr0rpw0000gn/T/stack15361/vector-sized-0.4.0.0/src/Data/Vector/Generic/Sized.hs:299:11:
        Couldn't match type ‘(n + m0) + 1’ with ‘(n + m) + 1’
        NB: ‘+’ is a type function, and may not be injective
        The type variable ‘m0’ is ambiguous
        Expected type: Vector v ((n + m) + 1) a -> Proxy n -> a
          Actual type: Vector v ((n + m0) + 1) a -> Proxy n -> a
        In the ambiguity check for the type signature for ‘index'’:
          index' :: forall (v :: * -> *) (n :: Nat) (m :: Nat) a.
                    (KnownNat n, KnownNat m, VG.Vector v a) =>
                    Vector v ((n + m) + 1) a -> Proxy n -> a
        To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
        In the type signature for ‘index'’:
          index' :: forall v n m a. (KnownNat n,
                                     KnownNat m,
                                     VG.Vector v a) =>
                    Vector v ((n + m) + 1) a -> Proxy n -> a
```

on LTS 6.24

**Comment by expipiplus1** [comment]
So it seems to fail to compile with 7.10.3.

I recommend you to upgrade to 8.0.1 if possible, otherwise I'd welcome a patch to implement support for 7.10.3.

For now I'll raise the lower bound on base to give a better error message.

Thanks!
